services:
  steel:
    build: .
    image: steel
    depends_on:
      redis:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 5001 --reload
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - ./output:/app/output
      - ./src/ai/weights:/app/src/ai/weights
      - ./sample:/app/sample
    environment:
      - REDIS_HOST=redis
      - PYTHONPATH=/app/src
    ports:
      - "5001:5001"
    env_file: .env

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5